@host=http://localhost:5117/v1

GET {{host}}/costumer/listAll
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiZDQxZTVmMC1jOTIwLTRlOWUtYTc5NC1kYTY5ODZhYTQyMGMiLCJnaXZlbl9uYW1lIjoiSm9obiIsImZhbWlseV9uYW1lIjoiRG9lIiwianRpIjoiZTgxNjAxZDItZDJhMy00ZjA0LWEzZTYtOTliYmFhZjJmMzk2IiwiZXhwIjoxNzQyNzY2Mjg1LCJpc3MiOiJSZXZDb21wYW55IiwiYXVkIjoiUmV2Q29tcGFueSJ9.OZn5iUEXpxeeW1GtZuVoqW9fbvGb5vCOw4rKVayJvMs


