name: .NET CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


defaults:
  run:
    working-directory: ./backend

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      PROJECT_PATH: ./RevCompany.sln
      

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: Build
      run: dotnet build ${{ env.PROJECT_PATH }} --no-restore
  
  test:
    runs-on: ubuntu-latest
    needs:
      - build
    env:
      PROJECT_PATH: ./RevCompany.sln
      TEST_PATH: ./Test/RevCompany.UnitTest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: Build
      run: dotnet build ${{ env.PROJECT_PATH }} --no-restore
        
    - name: Run Tests
      run: dotnet test ${{ env.TEST_PATH }} --no-build --verbosity normal
